#os: Previous Visual Studio 2015
#os: test-vs2015-hyperv
version: 1.0.{build}
configuration: Release
environment:
  AutoParameterizationWebConfigConnectionStrings: False

install:
- set PATH=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;%PATH%

before_build:
- cmd: appveyor-retry nuget restore
build:
  publish_wap: true
  verbosity: minimal
after_build:
- ps: Get-Path
