version: 1.0.{build}
configuration: Release
environment:
  AutoParameterizationWebConfigConnectionStrings: False
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  verbosity: minimal
test: off
