os: Previous Visual Studio 2015
version: 1.0.{build}
configuration: Release
environment:
  AutoParameterizationWebConfigConnectionStrings: False
before_build:
- cmd: appveyor-retry nuget restore
build:
  publish_wap: true
  verbosity: minimal
